"""empty message

Revision ID: 51137426afd0
Revises: f78dcf15589c
Create Date: 2022-07-26 23:44:58.737126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51137426afd0'
down_revision = 'f78dcf15589c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_iris_6_index', table_name='iris_6')
    op.drop_table('iris_6')
    op.add_column('users', sa.Column('db_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'db_count')
    op.create_table('iris_6',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sepal_length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sepal_width', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('petal_length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('petal_width', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('species', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_iris_6_index', 'iris_6', ['index'], unique=False)
    # ### end Alembic commands ###
