"""empty message

Revision ID: 5b1d2f845d20
Revises: c92ccc866068
Create Date: 2022-07-23 00:27:58.317822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1d2f845d20'
down_revision = 'c92ccc866068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
