"""empty message

Revision ID: c92ccc866068
Revises: 43b7b0a2641e
Create Date: 2022-07-23 00:18:26.924779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92ccc866068'
down_revision = '43b7b0a2641e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'other')
    # ### end Alembic commands ###
