"""empty message

Revision ID: f78dcf15589c
Revises: 
Create Date: 2022-07-23 22:02:56.389326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78dcf15589c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'other')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('other', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
